build_root:
  image_stream_tag:
    name: builder
    namespace: open-cluster-management
    tag: go1.16-linux-amd64
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: lint
  commands: |
    export SELF="make -f Makefile.prow"
    make -f Makefile.prow lint
  container:
    from: src
zz_generated_metadata:
  branch: release-2.3
  org: open-cluster-management
  repo: hub-crds
